package com.enablero.todo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.enablero.todo.converter.LocalDateTimeConverter;
import com.enablero.todo.model.TodoStatus;

import java.time.LocalDateTime;

@DynamoDBTable(tableName = "todo")
public class Todo {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    @DynamoDBRangeKey(attributeName = "email")
    private String email;

    private String title;
    private String description;
    private TodoStatus status;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime createdDt;

    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime updateDt;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "status")
    public TodoStatus getStatus() {
        return status;
    }

    public void setStatus(TodoStatus status) {
        this.status = status;
    }

    @DynamoDBAttribute(attributeName = "createdDt")
    public LocalDateTime getCreatedDt() {
        return createdDt;
    }

    public void setCreatedDt(LocalDateTime createdDt) {
        this.createdDt = createdDt;
    }

    @DynamoDBAttribute(attributeName = "updateDt")
    public LocalDateTime getUpdateDt() {
        return updateDt;
    }

    public void setUpdateDt(LocalDateTime updateDt) {
        this.updateDt = updateDt;
    }
}
